import { TimelineObject } from '../model/api/timeline-object'
import { Card } from '../model/card'
export const mockItemData: TimelineObject[] = [
  {
    objectID: 2487,
    isHighlight: false,
    accessionNumber: '42.149.3a, b',
    accessionYear: '1942',
    isPublicDomain: true,
    primaryImage:
      'https://images.metmuseum.org/CRDImages/ad/original/DP264251.jpg',
    primaryImageSmall:
      'https://images.metmuseum.org/CRDImages/ad/web-large/DP264251.jpg',
    additionalImages: [
      'https://images.metmuseum.org/CRDImages/ad/original/129479.jpg',
    ],
    constituents: null,
    department: 'The American Wing',
    objectName: 'Sugar bowl',
    title: 'Covered Sugar Bowl',
    culture: 'Chinese',
    period: '',
    dynasty: '',
    reign: '',
    portfolio: '',
    artistRole: '',
    artistPrefix: '',
    artistDisplayName: '',
    artistDisplayBio: '',
    artistSuffix: '',
    artistAlphaSort: '',
    artistNationality: '',
    artistBeginDate: '',
    artistEndDate: '',
    artistGender: '',
    artistWikidata_URL: '',
    artistULAN_URL: '',
    objectDate: '1770–1830',
    objectBeginDate: 1770,
    objectEndDate: 1830,
    medium: 'Porcelain',
    dimensions: 'H. 5 3/4 in. (14.6 cm)',
    measurements: [
      {
        elementName: 'Overall',
        elementDescription: null,
        elementMeasurements: { Height: 14.6 },
      },
    ],
    creditLine: 'Gift of Mrs. J. Insley Blair, 1942',
    geographyType: 'Made in',
    city: '',
    state: '',
    county: '',
    country: 'China',
    region: '',
    subregion: '',
    locale: '',
    locus: '',
    excavation: '',
    river: '',
    classification: '',
    rightsAndReproduction: '',
    linkResource: '',
    metadataDate: '2021-04-06T04:41:04.967Z',
    repository: 'Metropolitan Museum of Art, New York, NY',
    objectURL: 'https://www.metmuseum.org/art/collection/search/2487',
    tags: [
      {
        term: 'Eagles',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300250049',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q2092297',
      },
    ],
    objectWikidata_URL: '',
    isTimelineWork: false,
    GalleryNumber: '774',
  },
  {
    objectID: 976,
    isHighlight: false,
    accessionNumber: '10.149.75',
    accessionYear: '1910',
    isPublicDomain: true,
    primaryImage:
      'https://images.metmuseum.org/CRDImages/ad/original/DP258638.jpg',
    primaryImageSmall:
      'https://images.metmuseum.org/CRDImages/ad/web-large/DP258638.jpg',
    additionalImages: [],
    constituents: null,
    department: 'The American Wing',
    objectName: 'Bread plate',
    title: 'Bread Plate',
    culture: 'Chinese, for American market',
    period: '',
    dynasty: '',
    reign: '',
    portfolio: '',
    artistRole: '',
    artistPrefix: '',
    artistDisplayName: '',
    artistDisplayBio: '',
    artistSuffix: '',
    artistAlphaSort: '',
    artistNationality: '',
    artistBeginDate: '',
    artistEndDate: '',
    artistGender: '',
    artistWikidata_URL: '',
    artistULAN_URL: '',
    objectDate: '1785–90',
    objectBeginDate: 1785,
    objectEndDate: 1790,
    medium: 'Porcelain',
    dimensions: 'Diam. 6 1/4 in. (15.9 cm)',
    measurements: [
      {
        elementName: 'Other',
        elementDescription: 'Object diameter',
        elementMeasurements: { Diameter: 15.9 },
      },
    ],
    creditLine: 'Bequest of James T. Woodward, 1910',
    geographyType: 'Made in',
    city: '',
    state: '',
    county: '',
    country: 'China',
    region: '',
    subregion: '',
    locale: '',
    locus: '',
    excavation: '',
    river: '',
    classification: '',
    rightsAndReproduction: '',
    linkResource: '',
    metadataDate: '2021-04-06T04:41:04.967Z',
    repository: 'Metropolitan Museum of Art, New York, NY',
    objectURL: 'https://www.metmuseum.org/art/collection/search/976',
    tags: [
      {
        term: 'Coat of Arms',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300126352',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q14659',
      },
      {
        term: 'Birds',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300266506',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q5113',
      },
      {
        term: 'Flowers',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300132399',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q506',
      },
    ],
    objectWikidata_URL: '',
    isTimelineWork: false,
    GalleryNumber: '774',
  },
  {
    objectID: 45734,
    isHighlight: false,
    accessionNumber: '36.100.45',
    accessionYear: '1936',
    isPublicDomain: true,
    primaryImage:
      'https://images.metmuseum.org/CRDImages/as/original/DP251139.jpg',
    primaryImageSmall:
      'https://images.metmuseum.org/CRDImages/as/web-large/DP251139.jpg',
    additionalImages: [
      'https://images.metmuseum.org/CRDImages/as/original/DP251138.jpg',
      'https://images.metmuseum.org/CRDImages/as/original/DP251120.jpg',
    ],
    constituents: [
      {
        constituentID: 11986,
        role: 'Artist',
        name: 'Kiyohara Yukinobu',
        constituentULAN_URL: 'http://vocab.getty.edu/page/ulan/500034433',
        constituentWikidata_URL: 'https://www.wikidata.org/wiki/Q11560527',
        gender: 'Female',
      },
    ],
    department: 'Asian Art',
    objectName: 'Hanging scroll',
    title: 'Quail and Millet',
    culture: 'Japan',
    period: 'Edo period (1615–1868)',
    dynasty: '',
    reign: '',
    portfolio: '',
    artistRole: 'Artist',
    artistPrefix: '',
    artistDisplayName: 'Kiyohara Yukinobu',
    artistDisplayBio: 'Japanese, 1643–1682',
    artistSuffix: '',
    artistAlphaSort: 'Kiyohara Yukinobu',
    artistNationality: 'Japanese',
    artistBeginDate: '1643',
    artistEndDate: '1682',
    artistGender: 'Female',
    artistWikidata_URL: 'https://www.wikidata.org/wiki/Q11560527',
    artistULAN_URL: 'http://vocab.getty.edu/page/ulan/500034433',
    objectDate: 'late 17th century',
    objectBeginDate: 1667,
    objectEndDate: 1682,
    medium: 'Hanging scroll; ink and color on silk',
    dimensions: '46 5/8 x 18 3/4 in. (118.4 x 47.6 cm)',
    measurements: [
      {
        elementName: 'Overall',
        elementDescription: null,
        elementMeasurements: {
          Height: 118.4,
          Width: 47.6,
        },
      },
    ],
    creditLine: 'The Howard Mansfield Collection, Purchase, Rogers Fund, 1936',
    geographyType: '',
    city: '',
    state: '',
    county: '',
    country: '',
    region: '',
    subregion: '',
    locale: '',
    locus: '',
    excavation: '',
    river: '',
    classification: 'Paintings',
    rightsAndReproduction: '',
    linkResource: '',
    metadataDate: '2020-09-14T12:26:37.48Z',
    repository: 'Metropolitan Museum of Art, New York, NY',
    objectURL: 'https://www.metmuseum.org/art/collection/search/45734',
    tags: [
      {
        term: 'Birds',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300266506',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q5113',
      },
    ],
    objectWikidata_URL: 'https://www.wikidata.org/wiki/Q29910832',
    isTimelineWork: false,
    GalleryNumber: '',
  },
  {
    objectID: 436965,
    isHighlight: false,
    accessionNumber: '1976.201.14',
    accessionYear: '1976',
    isPublicDomain: true,
    primaryImage:
      'https://images.metmuseum.org/CRDImages/ep/original/DT1562.jpg',
    primaryImageSmall:
      'https://images.metmuseum.org/CRDImages/ep/web-large/DT1562.jpg',
    additionalImages: [],
    constituents: [
      {
        constituentID: 162094,
        role: 'Artist',
        name: 'Edouard Manet',
        constituentULAN_URL: 'http://vocab.getty.edu/page/ulan/500010363',
        constituentWikidata_URL: 'https://www.wikidata.org/wiki/Q40599',
        gender: '',
      },
    ],
    department: 'European Paintings',
    objectName: 'Painting',
    title: 'The Monet Family in Their Garden at Argenteuil',
    culture: '',
    period: '',
    dynasty: '',
    reign: '',
    portfolio: '',
    artistRole: 'Artist',
    artistPrefix: '',
    artistDisplayName: 'Edouard Manet',
    artistDisplayBio: 'French, Paris, France 1832–1883 Paris',
    artistSuffix: '',
    artistAlphaSort: 'Manet, Edouard',
    artistNationality: 'French',
    artistBeginDate: '1832',
    artistEndDate: '1883',
    artistGender: '',
    artistWikidata_URL: 'https://www.wikidata.org/wiki/Q40599',
    artistULAN_URL: 'http://vocab.getty.edu/page/ulan/500010363',
    objectDate: '1874',
    objectBeginDate: 1874,
    objectEndDate: 1874,
    medium: 'Oil on canvas',
    dimensions: '24 x 39 1/4 in. (61 x 99.7 cm)',
    measurements: [
      {
        elementName: 'Frame',
        elementDescription: null,
        elementMeasurements: {
          Depth: 9.525,
          Height: 86.3602,
          Width: 123.8252,
        },
      },
      {
        elementName: 'Overall',
        elementDescription: null,
        elementMeasurements: { Height: 61, Width: 99.7 },
      },
    ],
    creditLine: 'Bequest of Joan Whitney Payson, 1975',
    geographyType: '',
    city: '',
    state: '',
    county: '',
    country: '',
    region: '',
    subregion: '',
    locale: '',
    locus: '',
    excavation: '',
    river: '',
    classification: 'Paintings',
    rightsAndReproduction: '',
    linkResource: '',
    metadataDate: '2022-06-02T12:28:57.13Z',
    repository: 'Metropolitan Museum of Art, New York, NY',
    objectURL: 'https://www.metmuseum.org/art/collection/search/436965',
    tags: [
      {
        term: 'Gardens',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300008090',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q1107656',
      },
      {
        term: 'Men',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300025928',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q8441',
      },
      {
        term: 'Women',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300025943',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q467',
      },
      {
        term: 'Family',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300435378',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q8436',
      },
    ],
    objectWikidata_URL: 'https://www.wikidata.org/wiki/Q19911640',
    isTimelineWork: true,
    GalleryNumber: '818',
  },
  {
    objectID: 191807,
    isHighlight: false,
    accessionNumber: '11.173.5',
    accessionYear: '1911',
    isPublicDomain: true,
    primaryImage:
      'https://images.metmuseum.org/CRDImages/es/original/DP-13618-009.jpg',
    primaryImageSmall:
      'https://images.metmuseum.org/CRDImages/es/web-large/DP-13618-009.jpg',
    additionalImages: [
      'https://images.metmuseum.org/CRDImages/es/original/DP-13618-010.jpg',
      'https://images.metmuseum.org/CRDImages/es/original/131252.jpg',
      'https://images.metmuseum.org/CRDImages/es/original/131249.jpg',
    ],
    constituents: [
      {
        constituentID: 162325,
        role: 'Artist',
        name: 'Auguste Rodin',
        constituentULAN_URL: 'http://vocab.getty.edu/page/ulan/500016619',
        constituentWikidata_URL: 'https://www.wikidata.org/wiki/Q30755',
        gender: '',
      },
    ],
    department: 'European Sculpture and Decorative Arts',
    objectName: 'Statuette',
    title: 'Beside the Sea',
    culture: '',
    period: '',
    dynasty: '',
    reign: '',
    portfolio: '',
    artistRole: 'Artist',
    artistPrefix: '',
    artistDisplayName: 'Auguste Rodin',
    artistDisplayBio: 'French, Paris 1840–1917 Meudon',
    artistSuffix: '',
    artistAlphaSort: 'Rodin, Auguste',
    artistNationality: 'French',
    artistBeginDate: '1840',
    artistEndDate: '1917',
    artistGender: '',
    artistWikidata_URL: 'https://www.wikidata.org/wiki/Q30755',
    artistULAN_URL: 'http://vocab.getty.edu/page/ulan/500016619',
    objectDate: 'ca. 1907',
    objectBeginDate: 1902,
    objectEndDate: 1912,
    medium: 'Marble',
    dimensions:
      'Overall (wt. confirmed): 23 1/2 × 34 1/2 × 23 1/4 in., 527 lb. (59.7 × 87.6 × 59.1 cm, 239 kg)',
    measurements: [
      {
        elementName: 'Overall',
        elementDescription: 'wt. confirmed',
        elementMeasurements: {
          Depth: 59.1,
          Height: 59.7,
          Weight: 239.04564,
          Width: 87.6,
        },
      },
    ],
    creditLine: 'Gift of Thomas F. Ryan, 1910',
    geographyType: '',
    city: '',
    state: '',
    county: '',
    country: '',
    region: '',
    subregion: '',
    locale: '',
    locus: '',
    excavation: '',
    river: '',
    classification: 'Sculpture',
    rightsAndReproduction: '',
    linkResource: '',
    metadataDate: '2022-06-02T12:28:57.13Z',
    repository: 'Metropolitan Museum of Art, New York, NY',
    objectURL: 'https://www.metmuseum.org/art/collection/search/191807',
    tags: [
      {
        term: 'Female Nudes',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300189568',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q40446',
      },
    ],
    objectWikidata_URL: '',
    isTimelineWork: false,
    GalleryNumber: '800',
  },
]
export const mockCardData = (i = 0) => {
  return {
    id: mockItemData[i].objectID,
    content: mockItemData[i].title,
    year: mockItemData[i].objectBeginDate,
    primaryImageSmall: mockItemData[i].primaryImageSmall,
  } as Card
}
